Exception homework
Jengero/C_Sharp pull request #10
Opened 2023-07-06 20:29 UTC by Jengero

2023-07-07 21:33 UTC, MariaEroshevich requested changes, later dismissed

2023-07-07 21:33 UTC, MariaEroshevich commented on CSharpException/CSharpException/ReadDoubleFromConsole.cs
> +    internal static class ReadDoubleFromConsole
better to name class like ConsoleReader

2023-07-07 21:33 UTC, MariaEroshevich commented on CSharpException/CSharpException/ReadDoubleFromConsole.cs
> +
remove spaces

2023-07-07 21:33 UTC, MariaEroshevich commented on CSharpException/CSharpException/Program.cs
> +    if (sideOne > sideTwo + sideThree) { throw new SideValueException(sideOne, sideTwo, sideThree); }
Move this verifications to separate method in Tringle class. Then call this method in try catch construction here.

2023-07-07 21:33 UTC, MariaEroshevich commented on CSharpException/CSharpException/Program.cs
> +    return;
remove return.

2023-07-07 21:33 UTC, MariaEroshevich commented on CSharpException/CSharpException/Triangle.cs
> +        private double _firstSide;
Fields should go first, then properties. And add spaces between properties.

2023-07-11 19:36 UTC, dnnyhlwdplc approved these changes

2023-07-11 19:36 UTC, dnnyhlwdplc commented on CSharpException/CSharpException/ReadDoubleFromConsole.cs
> +    internal static class ReadDoubleFromConsole
Why do you have unused class here? I see that you have console reader already :)

2023-07-11 19:36 UTC, dnnyhlwdplc commented on CSharpLinq/CSharpLinq/Program.cs
> +//List<int> numbersToDivide = new() { 32, 50, 40, 77, 36, 93, 57, 4, 37, 7 };
please be careful about changes in PR :)
I see LINQ homework here :)

2023-07-11 21:53 UTC, merged